/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.server

import io.jsonwebtoken.Claims
import io.jsonwebtoken.JwtParser
import io.jsonwebtoken.Jwts

val parser: JwtParser = Jwts
        .parser()
        .setSigningKeyResolver(ClassPathSigningKeyResolver())
        .requireIssuer("https://dev-773716.okta.com/oauth2/default")

fun main() {

    val accessToken = "some-token"

    val claims = parser.parse<Claims>(accessToken, JwtHandler)

    println(claims)
}

